[["概念"]]
"圏" = "トルコ語"
"tts対象" = "tr-TR-AhmetNeural"
"記述" = "köpük"
"読み方" = "キョプュク"
"意味" = "泡"

[["概念"]]
"圏" = "トルコ語"
"tts対象" = "tr-TR-EmelNeural"
"記述" = "Harika"
"読み方" = ""
"意味" = "最高"

[["概念"]]
"圏" = "中国語"
"tts対象" = "zh-CN-XiaoxiaoNeural"
"記述" = "馒头"
"読み方" = "馒头"
"意味" = "馒头"

[["概念"]]
"圏" = "中国語"
"tts対象" = "zh-CN-XiaoxiaoNeural"
"記述" = "菜谱"
"読み方" = "菜谱"
"意味" = "菜谱"
